@HostAddress = https://localhost:7069
### Create a Movie
POST {{HostAddress}}/movies
Content-Type: application/json

{
  "title": "Test Name 2",
  "releaseYear": 2022,
  "description": "Test description 2",
  "genreIds": ["2360343a-93d0-485f-8182-552434ae7179", "65fa3cc9-3f4d-42fb-8b1c-c1dcd789d6ec"]
}

### Get a Movie by ID
GET {{HostAddress}}/movies/e35f3d1a-0558-4270-b118-594589bc2bdf
Content-Type: application/json

### Update a Movie
PUT {{HostAddress}}/movies/e35f3d1a-0558-4270-b118-594589bc2bdf
Content-Type: application/json

{
  "id": "e35f3d1a-0558-4270-b118-594589bc2bdf",
  "title": "Inception Comeback 3",
  "releaseYear": 2015,
  "description": "Vertion 2",
  "genreIds": ["2360343a-93d0-485f-8182-552434ae7179", "65fa3cc9-3f4d-42fb-8b1c-c1dcd789d6ec"]
}

### Delete a Movie
DELETE {{HostAddress}}/movies/aacb556f-f696-4750-969a-015b214ba9d1
Content-Type: application/json

### Rate a Movie
POST {{HostAddress}}/movies/e35f3d1a-0558-4270-b118-594589bc2bdf/rate
Content-Type: application/json

{
  "movieId": "e35f3d1a-0558-4270-b118-594589bc2bdf",
  "rating": 4
}

### Search Movies
GET {{HostAddress}}/movies/search?title=Test&genre=Sci-Fi
Content-Type: application/json
